# Generated by Django 4.2.7 on 2023-11-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alvos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alvo',
            name='identificador',
        ),
    ]
